# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import helloworld_pb2 as helloworld__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in helloworld_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/helloworld.Greeter/SayHello',
                request_serializer=helloworld__pb2.HelloRequest.SerializeToString,
                response_deserializer=helloworld__pb2.HelloReply.FromString,
                _registered_method=True)
        self.VCBC = channel.unary_unary(
                '/helloworld.Greeter/VCBC',
                request_serializer=helloworld__pb2.VCBCRequest.SerializeToString,
                response_deserializer=helloworld__pb2.VCBCReply.FromString,
                _registered_method=True)
        self.ClassicVCBC = channel.unary_unary(
                '/helloworld.Greeter/ClassicVCBC',
                request_serializer=helloworld__pb2.VCBCRequest.SerializeToString,
                response_deserializer=helloworld__pb2.VCBCReply.FromString,
                _registered_method=True)
        self.pVCBC = channel.unary_unary(
                '/helloworld.Greeter/pVCBC',
                request_serializer=helloworld__pb2.VCBCRequest.SerializeToString,
                response_deserializer=helloworld__pb2.VCBCReply.FromString,
                _registered_method=True)
        self.ABBA = channel.unary_unary(
                '/helloworld.Greeter/ABBA',
                request_serializer=helloworld__pb2.ABBARequest.SerializeToString,
                response_deserializer=helloworld__pb2.ABBAReply.FromString,
                _registered_method=True)
        self.ClassicABBA = channel.unary_unary(
                '/helloworld.Greeter/ClassicABBA',
                request_serializer=helloworld__pb2.ABBARequest.SerializeToString,
                response_deserializer=helloworld__pb2.ABBAReply.FromString,
                _registered_method=True)
        self.Propose = channel.unary_unary(
                '/helloworld.Greeter/Propose',
                request_serializer=helloworld__pb2.PRORequest.SerializeToString,
                response_deserializer=helloworld__pb2.PROReply.FromString,
                _registered_method=True)
        self.ClassicPropose = channel.unary_unary(
                '/helloworld.Greeter/ClassicPropose',
                request_serializer=helloworld__pb2.ClassicPRORequest.SerializeToString,
                response_deserializer=helloworld__pb2.ClassicPROReply.FromString,
                _registered_method=True)
        self.ClassicCommit = channel.unary_unary(
                '/helloworld.Greeter/ClassicCommit',
                request_serializer=helloworld__pb2.ClassicCommitRequest.SerializeToString,
                response_deserializer=helloworld__pb2.ClassicCommitReply.FromString,
                _registered_method=True)
        self.CollectProposal = channel.unary_unary(
                '/helloworld.Greeter/CollectProposal',
                request_serializer=helloworld__pb2.CPRORequest.SerializeToString,
                response_deserializer=helloworld__pb2.CPROReply.FromString,
                _registered_method=True)
        self.Recommend = channel.unary_unary(
                '/helloworld.Greeter/Recommend',
                request_serializer=helloworld__pb2.RECORequest.SerializeToString,
                response_deserializer=helloworld__pb2.RECOReply.FromString,
                _registered_method=True)
        self.SayHelloStreamReply = channel.unary_stream(
                '/helloworld.Greeter/SayHelloStreamReply',
                request_serializer=helloworld__pb2.HelloRequest.SerializeToString,
                response_deserializer=helloworld__pb2.HelloReply.FromString,
                _registered_method=True)
        self.SayHelloBidiStream = channel.stream_stream(
                '/helloworld.Greeter/SayHelloBidiStream',
                request_serializer=helloworld__pb2.HelloRequest.SerializeToString,
                response_deserializer=helloworld__pb2.HelloReply.FromString,
                _registered_method=True)
        self.ElectLeader = channel.unary_unary(
                '/helloworld.Greeter/ElectLeader',
                request_serializer=helloworld__pb2.ELeaderRequest.SerializeToString,
                response_deserializer=helloworld__pb2.ELeaderReply.FromString,
                _registered_method=True)


class GreeterServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VCBC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassicVCBC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pVCBC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ABBA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassicABBA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Propose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassicPropose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassicCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectProposal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recommend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloStreamReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloBidiStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ElectLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=helloworld__pb2.HelloRequest.FromString,
                    response_serializer=helloworld__pb2.HelloReply.SerializeToString,
            ),
            'VCBC': grpc.unary_unary_rpc_method_handler(
                    servicer.VCBC,
                    request_deserializer=helloworld__pb2.VCBCRequest.FromString,
                    response_serializer=helloworld__pb2.VCBCReply.SerializeToString,
            ),
            'ClassicVCBC': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassicVCBC,
                    request_deserializer=helloworld__pb2.VCBCRequest.FromString,
                    response_serializer=helloworld__pb2.VCBCReply.SerializeToString,
            ),
            'pVCBC': grpc.unary_unary_rpc_method_handler(
                    servicer.pVCBC,
                    request_deserializer=helloworld__pb2.VCBCRequest.FromString,
                    response_serializer=helloworld__pb2.VCBCReply.SerializeToString,
            ),
            'ABBA': grpc.unary_unary_rpc_method_handler(
                    servicer.ABBA,
                    request_deserializer=helloworld__pb2.ABBARequest.FromString,
                    response_serializer=helloworld__pb2.ABBAReply.SerializeToString,
            ),
            'ClassicABBA': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassicABBA,
                    request_deserializer=helloworld__pb2.ABBARequest.FromString,
                    response_serializer=helloworld__pb2.ABBAReply.SerializeToString,
            ),
            'Propose': grpc.unary_unary_rpc_method_handler(
                    servicer.Propose,
                    request_deserializer=helloworld__pb2.PRORequest.FromString,
                    response_serializer=helloworld__pb2.PROReply.SerializeToString,
            ),
            'ClassicPropose': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassicPropose,
                    request_deserializer=helloworld__pb2.ClassicPRORequest.FromString,
                    response_serializer=helloworld__pb2.ClassicPROReply.SerializeToString,
            ),
            'ClassicCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassicCommit,
                    request_deserializer=helloworld__pb2.ClassicCommitRequest.FromString,
                    response_serializer=helloworld__pb2.ClassicCommitReply.SerializeToString,
            ),
            'CollectProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectProposal,
                    request_deserializer=helloworld__pb2.CPRORequest.FromString,
                    response_serializer=helloworld__pb2.CPROReply.SerializeToString,
            ),
            'Recommend': grpc.unary_unary_rpc_method_handler(
                    servicer.Recommend,
                    request_deserializer=helloworld__pb2.RECORequest.FromString,
                    response_serializer=helloworld__pb2.RECOReply.SerializeToString,
            ),
            'SayHelloStreamReply': grpc.unary_stream_rpc_method_handler(
                    servicer.SayHelloStreamReply,
                    request_deserializer=helloworld__pb2.HelloRequest.FromString,
                    response_serializer=helloworld__pb2.HelloReply.SerializeToString,
            ),
            'SayHelloBidiStream': grpc.stream_stream_rpc_method_handler(
                    servicer.SayHelloBidiStream,
                    request_deserializer=helloworld__pb2.HelloRequest.FromString,
                    response_serializer=helloworld__pb2.HelloReply.SerializeToString,
            ),
            'ElectLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.ElectLeader,
                    request_deserializer=helloworld__pb2.ELeaderRequest.FromString,
                    response_serializer=helloworld__pb2.ELeaderReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('helloworld.Greeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/SayHello',
            helloworld__pb2.HelloRequest.SerializeToString,
            helloworld__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VCBC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/VCBC',
            helloworld__pb2.VCBCRequest.SerializeToString,
            helloworld__pb2.VCBCReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassicVCBC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/ClassicVCBC',
            helloworld__pb2.VCBCRequest.SerializeToString,
            helloworld__pb2.VCBCReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def pVCBC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/pVCBC',
            helloworld__pb2.VCBCRequest.SerializeToString,
            helloworld__pb2.VCBCReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ABBA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/ABBA',
            helloworld__pb2.ABBARequest.SerializeToString,
            helloworld__pb2.ABBAReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassicABBA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/ClassicABBA',
            helloworld__pb2.ABBARequest.SerializeToString,
            helloworld__pb2.ABBAReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Propose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/Propose',
            helloworld__pb2.PRORequest.SerializeToString,
            helloworld__pb2.PROReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassicPropose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/ClassicPropose',
            helloworld__pb2.ClassicPRORequest.SerializeToString,
            helloworld__pb2.ClassicPROReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassicCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/ClassicCommit',
            helloworld__pb2.ClassicCommitRequest.SerializeToString,
            helloworld__pb2.ClassicCommitReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/CollectProposal',
            helloworld__pb2.CPRORequest.SerializeToString,
            helloworld__pb2.CPROReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recommend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/Recommend',
            helloworld__pb2.RECORequest.SerializeToString,
            helloworld__pb2.RECOReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SayHelloStreamReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/helloworld.Greeter/SayHelloStreamReply',
            helloworld__pb2.HelloRequest.SerializeToString,
            helloworld__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SayHelloBidiStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/helloworld.Greeter/SayHelloBidiStream',
            helloworld__pb2.HelloRequest.SerializeToString,
            helloworld__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ElectLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/ElectLeader',
            helloworld__pb2.ELeaderRequest.SerializeToString,
            helloworld__pb2.ELeaderReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CentralStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ElectLeader = channel.unary_unary(
                '/helloworld.Central/ElectLeader',
                request_serializer=helloworld__pb2.ELeaderRequest.SerializeToString,
                response_deserializer=helloworld__pb2.ELeaderReply.FromString,
                _registered_method=True)
        self.CommitteeSelection = channel.unary_stream(
                '/helloworld.Central/CommitteeSelection',
                request_serializer=helloworld__pb2.CSelectionRequest.SerializeToString,
                response_deserializer=helloworld__pb2.CSelectionReply.FromString,
                _registered_method=True)


class CentralServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ElectLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitteeSelection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CentralServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ElectLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.ElectLeader,
                    request_deserializer=helloworld__pb2.ELeaderRequest.FromString,
                    response_serializer=helloworld__pb2.ELeaderReply.SerializeToString,
            ),
            'CommitteeSelection': grpc.unary_stream_rpc_method_handler(
                    servicer.CommitteeSelection,
                    request_deserializer=helloworld__pb2.CSelectionRequest.FromString,
                    response_serializer=helloworld__pb2.CSelectionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.Central', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('helloworld.Central', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Central(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ElectLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Central/ElectLeader',
            helloworld__pb2.ELeaderRequest.SerializeToString,
            helloworld__pb2.ELeaderReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitteeSelection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/helloworld.Central/CommitteeSelection',
            helloworld__pb2.CSelectionRequest.SerializeToString,
            helloworld__pb2.CSelectionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
